name = "Om Ambadas Bade"
rol = """B.Tech in Computer Engineering 
(Honors in data science)"""
email = "ombade364@gmail.com"
phone = "9022157947"
birthday = "NOV 21, 2003"
location = "Ahmednagar , Maharastra ,India"
avatar = "https://avatars.githubusercontent.com/u/71856738?s=400&u=00353c8f6a51b717b50856dc6ad41548b7cb8a6a&v=4"
username = "ombade" # <-- github user name
googlemaps = "https://maps.app.goo.gl/9S9Rn24H9pTYhhbi8" 
presentation = """
A dedicated, observant, and passionate learner, always eager to
gain hands-on experience and explore new domains through
various platforms, online and offline.
"""
