[[project]]
title = "Crop Yield Prediction"
category = "Machine Learning"
image = "https://github.com/ombade/Crop_Yield/blob/main/CropYield-Prediction.png?raw=true"
url = "https://github.com/ombade/Crop_Yield"

[[project]]
title = "Decision Tree Classifier"
category = "Machine Learning"
image = "src/images/Desion Tree"
url = "https://github.com/ombade/decision-tree-classifier"

[[project]]
title = "Notepad Application"
category = "Python Scripting"
image = "https://github.com/ombade/notepad-using-python/blob/main/notepad.png?raw=true"
url = "https://github.com/ombade/notepad-using-python"

[[project]]
title = "Celebal Summer Internship 2k24"
category = "Machine Learning"
image = "https://github.com/ombade/Celebal_Summer_Internship_2k24/blob/main/internship.png?raw=true"
url = "https://github.com/ombade/Celebal_Summer_Internship_2k24"

[[project]]
title = "Flipkart Web Scraping"
category = "Web Scraping"
image = "src/images/WebScraping"
url = "https://github.com/ombade/flickart_review_scraping"

[[project]]
title = "Geolocation App"
category = "Web Development"
image = "src/images/GeoLocation"
url = "https://github.com/ombade/geolocation-app"


[[project]]
title = "Financial Calcutor"
category = "Web Development"
image = "src/images/fincal"
url = "https://github.com/ombade/Finance_cal?tab=readme-ov-file"


[[project]]
title = "Todo List Web App"
category = "Web Development"
image = "https://github.com/ombade/todo-list-web-app/blob/main/todo-list.png?raw=true"
url = "https://github.com/ombade/todo-list-web-app"



