############## Education config #################
#################################################

[[education]]
title = "B.Tech in Computer Science (Honors in Data Science)"
timeline = "July 2021 — July 2025 (expected)"
description = "Sanjivani College of Engineering, Kopargaon. CGPA: 7.9"

[[education]]
title = "HSC, Maharashtra State Board"
timeline = "April 2019 — April 2021"
description = "Arts Commerce and Science College, Shevgaon. Percentage: 91.50"

[[education]]
title = "SSC, Maharashtra State Board"
timeline = "May 2014 — April 2019"
description = "Shevgaon English Medium School, Shevgaon. Percentage: 87.80"

############## Experience config ################
#################################################

[[experience]]
title = "Campus Ambassador"
timeline = "June 2022 — June 2023"
description = "GeeksForGeeks, Noida. Represented GeeksForGeeks, organized coding events, workshops, and contests. Collaborated with clubs and faculty, mentored students, and provided programming support."

[[experience]]
title = "Internship Trainee"
timeline = "April 2023 — June 2023"
description = "Vedic City, Mumbai. Collaborated on a Machine Learning and Development project for optimizing the food booking system. Developed web applications using Flask and enhanced system performance and user experience."

############## Skills config ####################
#################################################
[skills] 
title = "Technical Skills"
enabled = true
show_bar = true
show_value = true

[[skill]]
title = "SQL"
value = "80%"

[[skill]]
title = "Python"
value = "90%"

[[skill]]
title = "C"
value = "75%"

[[skill]]
title = "C++"
value = "75%"

[[skill]]
title = "VS Code"
value = "85%"

[[skill]]
title = "GitHub"
value = "80%"

[[skill]]
title = "Gitbash"
value = "75%"

[[skill]]
title = "PowerBI"
value = "70%"

[[skill]]
title = "Postman"
value = "70%"

[[skill]]
title = "Flask"
value = "85%"

[[skill]]
title = "React JS"
value = "80%"

[[skill]]
title = "Android Studio"
value = "65%"

[[skill]]
title = "Spring Boot"
value = "60%"

[[skill]]
title = "JSP"
value = "60%"

[[skill]]
title = "Servlet"
value = "60%"

[[skill]]
title = "AWS"
value = "70%"

[[skill]]
title = "MySQL"
value = "75%"

[[skill]]
title = "MongoDB"
value = "70%"

############## Language config ##################
#################################################
[languages]
title = "Languages"
enabled = true
show_bar = true
show_value = true

[[language]]
title = "English"
value = "90%"

[[language]]
title = "Hindi"
value = "80%"

[[language]]
title = "Marathi"
value = "85%"
